### ISSUE TITLE
Search terms break characters in breadcrumb on page load. ( departament )

### ISSUE THREAD

**Issue by micas06gua** [vtex-apps/breadcrumb#47]
## Expected Behavior

When filtering for a term, breadcrumb should not have character breaks when reloading the page.

## Current Behavior

When accessing the department : "infantil" using the render-runtime, then filtering by "idade" for instace "0 a 4 anos", the text that comes in the breadcrumbs works correctly, but when reloading the filtered page, the breadcrumb gets special characters, probably because of the white spaces between the letters.

## Steps to Reproduce (for bugs)

1. Go to https://newbalance.myvtex.com
2. Choose the department : "infantil" , then filter by "idade"
3. Wait for the page to finish loading, then reload it
4. The breadcrumb will be broken with special characters.

bug - >

https://ibb.co/KrKccHw
https://ibb.co/619Ct7P

## Your Environment

* Windows 7
* Chrome 75

**Comment by Klynger** [comment]
Closing this issue, if the problem persists, create another issue in https://github.com/vtex-apps/store-discussion
