### ISSUE TITLE
Separator Icon missing customization

### ISSUE THREAD

**Issue by cristian-milea** [vtex-apps/breadcrumb#62]
There is no option to change icon from caret arrow to anything else. How do i change this?

## Expected Behavior
A prop should exist, "separatorIcon": ["text", "icon", "custom"]
 
## Current Behavior
no option of changing

## Context

My client wants dash instead of arrow.

**Comment by Klynger** [comment]
If this feature wasn't implemented yet and you need it, please create this issue again in https://github.com/vtex-apps/store-discussion
